# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1z0uoNH8nWrJIA4NPK7Ka1EcWNxXUqGMY
"""

import hashlib
import base64

salt_key = "fixed_salt_key"

# This will encrypt the password using a salt key - Run this on your signup button by passing the entered password
def saltify(password: str, salt: str) -> str:
    salt_bytes = salt.encode('utf-8')
    hash_obj = hashlib.pbkdf2_hmac('sha256', password.encode('utf-8'), salt_bytes, 100000)
    return base64.b64encode(hash_obj).decode('utf-8') # Save this value into your database - No need to save the entered password

# This will verify the password - Run this while signing in by passing the password, salt key & stored password from db
def verifyPassword(password: str, salt: str, storedPassword: str) -> bool:
    new_hash = saltify(password, salt)
    return new_hash == storedPassword


print("---------------------------SIGNING UP-------------------------")

username = input("Enter Username To Register: ")
password = input("Password To Register: ")

registeredPassword = saltify(password, salt_key);
print("This Is Your Encrypted Password:", registeredPassword)

print("---------------------------SIGNING IN-------------------------")

signInUser = input("Enter Signin Username: ")
signInPassword = input("Enter Signin Password: ")

if (username == signInUser and verifyPassword(signInPassword, salt_key, registeredPassword)):
  print("Sign-in successful")

else:
  print("Signin Unsuccessful - Check Username/Password")

